nicdebray/fluidata

db/migrate/20181112153749_add_columns_to_users.rb
db/schema.rb

Added fields to Users DB and migrated.

added fields to Users DB

---

app/models/user.rb

Updating user model

---

app/controllers/graph_blocks_controller.rb
app/models/graph_block.rb
app/models/report.rb
config/routes.rb
db/migrate/20181113125905_create_graph_blocks.rb
db/schema.rb
test/controllers/graph_blocks_controller_test.rb
test/models/graph_block_test.rb

Added graph model 
Put belong_to in report model for all blocks

added graph model and put belong_to in report model for all blocks

---

app/models/company.rb
app/models/graph_block.rb
app/models/kpi_block.rb
app/models/report.rb
app/models/text_block.rb
config/routes.rb

Relations and validations controllers

---

Gemfile
Gemfile.lock
app/policies/application_policy.rb
db/schema.rb

Punidt installed, not setup yet.

pundit installed, not setup

---

app/controllers/application_controller.rb
db/migrate/20181113144520_add_admin_to_users.rb
db/schema.rb

Added admin
Setup Applicationcontroller.

Installing pundit

---

app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

Added to User View Create and Edit:
* first_name
* last_name
* department
* admin

added necessary fields to create and edit user

---

app/controllers/application_controller.rb
app/models/user.rb
config/initializers/devise.rb

Fixed bug on check-in by removing validation on extra fields.

Fixed bug on check-in

---

app/models/user.rb
app/views/devise/registrations/new.html.erb

Added different departments into User form authorisation and User view - simple form.

Added departments into form and user model

---

app/controllers/application_controller.rb
app/controllers/graph_blocks_controller.rb
app/controllers/kpi_blocks_controller.rb
app/controllers/reports_controller.rb
app/controllers/text_blocks_controller.rb
app/models/report.rb
app/models/user.rb
app/views/reports/index.html.erb
app/views/reports/new.html.erb
app/views/text_blocks/create.html.erb

Removed Pundit, as it was throwing errors.
Start of links.

removed Pundit

---

app/controllers/text_blocks_controller.rb
app/views/companies/destroy.html.erb
app/views/graph_blocks/edit.html.erb
app/views/graph_blocks/index.html.erb
app/views/graph_blocks/new.html.erb
app/views/graph_blocks/show.html.erb
app/views/kpi_blocks/create.html.erb
app/views/kpi_blocks/destroy.html.erb
app/views/kpi_blocks/edit.html.erb
app/views/kpi_blocks/update.html.erb
app/views/reports/create.html.erb
app/views/reports/destroy.html.erb
app/views/reports/edit.html.erb
app/views/reports/index.html.erb
app/views/reports/new.html.erb
app/views/reports/show.html.erb
app/views/reports/update.html.erb
app/views/text_blocks/create.html.erb
app/views/text_blocks/destroy.html.erb
app/views/text_blocks/update.html.erb

All links on report pages added.

Added links on all report pages

---

app/models/user.rb

Uncommented validation departments.

Check regarding validation of departments

---

app/views/reports/index.html.erb

avoided last report being shown if none

---

app/views/reports/edit.html.erb
app/views/reports/index.html.erb

Last correction on Report links. 
Next: links in blocks.

Corrected all links in Reports

---

app/controllers/graph_blocks_controller.rb
app/controllers/kpi_blocks_controller.rb
app/controllers/text_blocks_controller.rb
app/views/graph_blocks/edit.html.erb
app/views/graph_blocks/new.html.erb
app/views/kpi_blocks/edit.html.erb
app/views/kpi_blocks/new.html.erb
app/views/reports/edit.html.erb
app/views/reports/index.html.erb
app/views/reports/show.html.erb
app/views/text_blocks/edit.html.erb
app/views/text_blocks/index.html.erb
app/views/text_blocks/new.html.erb

Added links in all blocks. All are working and saving as well. Links in reports were added before.
Next: links in / to Company.

All links ok

---

app/controllers/kpi_blocks_controller.rb
app/controllers/text_blocks_controller.rb
app/views/reports/edit.html.erb

Links on Reports Edit page added. Controllers not working yet.

links in paged edit

---

app/views/reports/edit.html.erb
app/views/reports/show.html.erb

Fixed issue in links for edit / show / destroy blocks.

Fixed links show/edit/destroy

---

app/assets/stylesheets/components/_card_index.scss
app/assets/stylesheets/components/_index.scss
app/views/reports/index.html.erb

First draft of reports index page.
Horizontal and vertical list working.

first scetch index page reports

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_card_index.scss
app/controllers/kpi_blocks_controller.rb
app/javascript/packs/application.js
app/views/reports/index.html.erb

Made some changes on Indexpage Report.
Drag and drop failed.

Little changes Index Reports page

---

app/views/reports/index.html.erb

Toggle star with event listener.

Stars change color when clicking

---

app/models/graph_block.rb
app/models/kpi_block.rb
app/models/text_block.rb
app/views/graph_blocks/edit.html.erb
app/views/graph_blocks/new.html.erb
app/views/kpi_blocks/edit.html.erb
app/views/kpi_blocks/new.html.erb
app/views/pages/home.html.erb
app/views/reports/index.html.erb
app/views/shared/_kpi.html.erb
app/views/text_blocks/edit.html.erb
app/views/text_blocks/new.html.erb

Linked button on startpage to overview reports page
Make 'order' not compulsary in blocks
Removed 'order' from forms.

linked button startpage and removed order

---

app/assets/stylesheets/components/_card_index.scss
app/views/reports/show.html.erb

Fixed front end for txt blocks on show page order.

Remove order

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_index.scss
app/controllers/reports_controller.rb
app/views/layouts/pdf_layout.html.erb
app/views/reports/show.html.erb
config/application.rb
config/initializers/mime_types.rb
config/initializers/wicked_pdf.rb

Added pdf sharing gem

---

app/controllers/application_controller.rb
app/models/user.rb
app/views/shared/_avatar.html.erb
db/migrate/20181119203716_add_column_to_users.rb
db/schema.rb

Avatar fixed: dummy when not logged in or no avatar and picture when user has avatar.

fixed avatar

---

app/assets/stylesheets/components/_navbar.scss

Made size cover to have correct ratio.

corrected size avatar

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_profile_page.scss
app/controllers/users_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/shared/_sidebar.html.erb
app/views/shared/_upload_avatar.html.erb
app/views/users/edit.html.erb
app/views/users/show.html.erb

Added new and edit pages User Profile.

created profile pages new and edit

---

app/controllers/reports_controller.rb
app/models/report.rb
app/views/reports/index.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_search.html.erb

Made blocks dependent from report.
Tab reports in navbar disappearing if not logged in.

made blocks dependent, reports in navbar disappearing if not logged in

---

app/assets/javascripts/application.js
app/controllers/reports_controller.rb
app/views/reports/index.html.erb

Fix delete buttons, which were not working due to unused line of code.

Search box

---

app/views/reports/index.html.erb

Fixed delete button after merging and braking

---

app/views/reports/index.html.erb

Added popup message when deleting on Report index page.

added confirm message delete on index page

---

app/assets/stylesheets/pdf.scss
app/controllers/reports_controller.rb
app/views/reports/pdf.html.erb
app/views/reports/pdf.pdf.erb

Work on pdf

---

app/views/reports/index.html.erb

Fixed search Bar and adapted search page to show search results.

fixed search

---

app/views/graph_blocks/edit.html.erb
app/views/graph_blocks/new.html.erb
app/views/kpi_blocks/edit.html.erb
app/views/kpi_blocks/new.html.erb

Removed autocomplete from calendars.

Stopped autocomplete

---

app/assets/stylesheets/components/_datepicker.scss
app/javascript/packs/application.js
app/views/reports/show.html.erb

Fixed html on show page and modified location datepicker slightly.

Fixed /ends and /divs
